//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using RepositoryLayer.AppContext;

//namespace RepositoryLayer.Migrations
//{
//    [DbContext(typeof(Context))]
//    [Migration("20220128174724_Second")]
//    partial class Second
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("RepositoryLayer.Entities.Note", b =>
//                {
//                    b.Property<long>("NoteId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Color")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("Createst")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Image")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsArchieve")
//                        .HasColumnType("bit");

//                    b.Property<bool>("IsPin")
//                        .HasColumnType("bit");

//                    b.Property<bool>("IsTrash")
//                        .HasColumnType("bit");

//                    b.Property<string>("Message")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("Modifiedat")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("Remainder")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("NoteId");

//                    b.ToTable("Notes");
//                });

//            modelBuilder.Entity("RepositoryLayer.Entities.User", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<DateTime?>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("FirstName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LastName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("ModifiedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Password")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
